### ISSUE TITLE
[英文搬家] 雲端物件儲存

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#119]
> lang
> - [ ] zh-Hant 
> - [x] En

## Source docs

- https://github.com/twcc/TWCC-Docs-en/tree/main/COS/0.%20Overview *1
> ![](https://i.imgur.com/sYl7ggl.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/COS/1.%20User%20Guides *8
> ![](https://i.imgur.com/FfqGN7t.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/COS/2.%20Tutorials *1
> ![](https://i.imgur.com/n757vHd.png)

(進入上方 GitHub > 點選截圖對應的文件 > 點開右上的 `Raw`，即可複製 markdown 內容)

## Target folders and files

- i18n\en\docusaurus-plugin-content-docs\current\cos *10

## To-dos

- refer to PPT [p.24 to p.36](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.p67) (複製檔案方式和中文不同，請參考上方 Source docs 的說明)

**Comment by Oysteranpu** [comment]
[檢視儲存體](https://github.com/twcc/TWCC-Docs-en/blob/main/COS/1.%20User%20Guides/2.%20%E6%AA%A2%E8%A6%96%E5%84%B2%E5%AD%98%E9%AB%94.md?plain=1) Tab內部列點消失
可能與 #85 問題相同
![image](https://user-images.githubusercontent.com/109254397/182767081-29316388-77e1-4b12-afe2-f40bc024d9a9.png)

**Comment by Oysteranpu** [comment]
> [檢視儲存體](https://github.com/twcc/TWCC-Docs-en/blob/main/COS/1.%20User%20Guides/2.%20%E6%AA%A2%E8%A6%96%E5%84%B2%E5%AD%98%E9%AB%94.md?plain=1) Tab內部列點消失 可能與 #85 問題相同 ![image](https://user-images.githubusercontent.com/109254397/182767081-29316388-77e1-4b12-afe2-f40bc024d9a9.png)

更新：多空幾行可以解決XD

**Comment by Oysteranpu** [comment]
[檔案加密](https://github.com/twcc/TWCC-Docs-en/blob/main/COS/1.%20User%20Guides/%E6%AA%94%E6%A1%88%E5%8A%A0%E5%AF%86_en.md)內沒有內容
![image](https://user-images.githubusercontent.com/109254397/182769140-e6f1e416-41fc-4feb-a902-11753ce9690a.png)

**Comment by Oysteranpu** [comment]
[使用 TWCC COS 備份同步、還原運算資料](https://github.com/twcc/TWCC-Docs-en/blob/main/COS/2.%20Tutorials/1.%20%E4%BD%BF%E7%94%A8%20TWCC%20COS%20%E5%82%99%E4%BB%BD%E5%90%8C%E6%AD%A5%E3%80%81%E9%82%84%E5%8E%9F%E9%81%8B%E7%AE%97%E8%B3%87%E6%96%99.md)這一頁
img發生錯誤 還在找方法解決
![image](https://user-images.githubusercontent.com/109254397/182771888-2d56ee5d-33fb-482c-80b0-9f093bdd5e1b.png)

**Comment by Oysteranpu** [comment]
> [使用 TWCC COS 備份同步、還原運算資料](https://github.com/twcc/TWCC-Docs-en/blob/main/COS/2.%20Tutorials/1.%20%E4%BD%BF%E7%94%A8%20TWCC%20COS%20%E5%82%99%E4%BB%BD%E5%90%8C%E6%AD%A5%E3%80%81%E9%82%84%E5%8E%9F%E9%81%8B%E7%AE%97%E8%B3%87%E6%96%99.md)這一頁 img發生錯誤 還在找方法解決 ![image](https://user-images.githubusercontent.com/109254397/182771888-2d56ee5d-33fb-482c-80b0-9f093bdd5e1b.png)

找到問題了：
15.的`<supercomputer account>`改成(supercomputer account)
info中若要放表格需前後空行
還有很多小細節的前後空行(救命)
