### ISSUE TITLE
[英文搬家] 高速檔案系統

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#120]
> lang
> - [ ] zh-Hant 
> - [x] En

## Source docs

- https://github.com/twcc/TWCC-Docs-en/tree/main/HFS/0.%20Overview *1
> ![](https://i.imgur.com/88JysLi.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/HFS/1.%20User%20Guides *3
> ![](https://i.imgur.com/Y8TPAhF.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/HFS/3.%20Other *1
> ![](https://i.imgur.com/HXxH8UF.png)

(進入上方 GitHub > 點選截圖對應的文件 > 點開右上的 `Raw`，即可複製 markdown 內容)

## Target folders and files

- i18n\en\docusaurus-plugin-content-docs\current\hfs *5

## To-dos

- refer to PPT [p.24 to p.36](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.p67) (複製檔案方式和中文不同，請參考上方 Source docs 的說明)

**Comment by Oysteranpu** [comment]
[服務概觀](https://github.com/twcc/TWCC-Docs-en/blob/main/HFS/0.%20Overview/1.%20%E6%9C%8D%E5%8B%99%E6%A6%82%E8%A7%80.md?plain=1)中的`<Supercomputer username>`會成小恐龍錯誤
目前先改成(Supercomputer username)
![image](https://user-images.githubusercontent.com/109254397/182773063-25f48f96-0234-4758-8f9d-691d827f036f.png)
