### ISSUE TITLE
[英文搬家] FAQ

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#140]
> lang
> - [ ] zh-Hant 
> - [x] En

## Source docs

- https://github.com/twcc/TWCC-Docs-en/tree/main/Account%20%26%20Project/4.%20FAQs *3：
> ![](https://i.imgur.com/MtjoxnW.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/CCS/4.%20FAQs *1
> ![](https://i.imgur.com/rDHqMrA.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/VCS/4.%20FAQs *1
> ![](https://i.imgur.com/2ju03ZI.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/TWNIA2/3.%20FAQs *1
> ![](https://i.imgur.com/rSViMFZ.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/COS/3.%20FAQs *1
> ![](https://i.imgur.com/3kDQoAj.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/HFS/2.%20FAQs *1
> ![](https://i.imgur.com/SXls27I.png)

- https://github.com/twcc/TWCC-Docs-en/tree/main/CLI/4.%20FAQs *2
> ![](https://i.imgur.com/Kkxs13J.png)

(進入上方 GitHub > 點選截圖對應的文件 > 點開右上的 `Raw`，即可複製 markdown 內容)

## Target folders and files
- i18n\en\docusaurus-plugin-content-docs\current\faq *10

## To-dos
- refer to PPT [p.24 to p.36](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.p67) (複製檔案方式和中文不同，請參考上方 Source docs 的說明)

**Comment by Oysteranpu** [comment]
產品概觀 有一處 
會員計畫與帳務 有四處
之後需要更新
![image](https://user-images.githubusercontent.com/109254397/183305523-0abfeb31-1a93-4938-a873-2fde4edf7917.png)

**Comment by VigaWei** [comment]
> 產品概觀 有一處 會員計畫與帳務 有四處 之後需要更新 ![image](https://user-images.githubusercontent.com/109254397/183305523-0abfeb31-1a93-4938-a873-2fde4edf7917.png)

後續 up-to-date 時安排處理 🙏
