### ISSUE TITLE
[DISCUSS] - 容器映像檔瀏覽器頁籤問題

### ISSUE THREAD

**Issue by Oysteranpu** [twcc/man-vip#163]
## Descriptions
[開發型容器-容器映像檔](https://man.twcc.ai/@twccdocs/ccs-concept-image-main-zh/%2F%40twccdocs%2Fccs-concept-image-tensorrtserver-zh)

## 目前狀況 (as is) 

title加上圖片後瀏覽器頁籤產生問題<br>
![image](https://user-images.githubusercontent.com/109254397/184083491-25c352a3-6bff-4e72-8444-9c3eedaad7ae.png)
- 

## 理想狀況 (to be)
瀏覽器頁籤應顯示為對應標題<br>
![image](https://user-images.githubusercontent.com/109254397/184083452-2e549416-c256-45e6-89bc-67d208b4990b.png)
- 

## Reference:
- zh: https://github.com/twcc/man-vip/issues/28
- zh: https://github.com/twcc/man-vip/issues/29
- en: https://github.com/twcc/man-vip/issues/117
- en: https://github.com/twcc/man-vip/issues/118

**Comment by Oysteranpu** [comment]
[高速檔案系統](https://man.twcc.ai/@twccdocs/doc-hfs-main-zh/%2F%40twccdocs%2Fhfs-overview-zh)以及[雲端物件儲存](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fcos-overview-zh)有相同問題

![image](https://user-images.githubusercontent.com/109254397/184087174-f8fd37f1-2835-4d79-a359-e22b07b79a4a.png)

- zh:https://github.com/twcc/man-vip/issues/30
- zh:https://github.com/twcc/man-vip/issues/31
- en:https://github.com/twcc/man-vip/issues/119
- en:https://github.com/twcc/man-vip/issues/120

**Comment by Oysteranpu** [comment]
參考[虛擬運算服務](https://man.twcc.vip/docs/vcs/intro/)應該能解決

![image](https://user-images.githubusercontent.com/109254397/184088999-68c654d5-522f-49ca-b9ad-4b6e905c9857.png)

**Comment by VigaWei** [comment]
👍👍 謝謝觀察!! 請幫忙直接在 meta data 內加上 title：

- title 請用下方 heading one # 後的內容
- 英文檔案也請同步做法

@chuchun211 也請注意上方的做法 🙏
