### ISSUE TITLE
[搬家調整] - 高速運算任務/任務型容器/release note  

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#177]
> lang
> - [x] zh-Hant 
> - [x] En

## Source docs

- zh: https://github.com/twcc/man-vip/issues/71
- en: https://github.com/twcc/man-vip/issues/121

## Target folders and files

如上述，也可直接參考 https://man.twcc.vip 上的內容：
- zh 路徑：`https://man.twcc.vip/` 之後的內容就是檔案路徑
- en 路徑： `https://man.twcc.vip/` 之後的內容，將`en/docs` 取代為 `i18n/en/docusaurus-plugin-content-docs/current` 即是檔案路徑

## To-dos
Note: 第 3、4、5 完成後請在 checkbox :heavy_check_mark: 

### 1. new doc：metadata 置入 source doc link

```
sync_original_production: 'url' 
sync_original_preview: 'url' 
```

- a. 請將上方 block 內容複製貼上至 doc 最上方 metadata 內
> ![](https://i.imgur.com/3Ojk258.png)
- b. `sync_original_production` 請貼 source doc 單篇的連結，非 bookmode 下的連結
- c. `sync_original_production` 直接將上方 production url 其中的 `@twccdocs` 改為 `@preview-twccdocs`
> ![](https://i.imgur.com/EgwR6zz.png)
- d. 英文版請直接複製中文版，將結尾 `zh` 改為 `en` (若中文版非 `zh` 結尾請留言紀錄 :pray:) 
> ![](https://i.imgur.com/aFgXGob.png)

###  2. 開啟 source doc (HackMD, en 請開 GitHub) & new doc (docusaurus)
> source doc ![](https://i.imgur.com/DdAcgct.png) 

> new doc ![](https://i.imgur.com/Uz1wNAa.png)

###  3. 比對網頁版 source doc vs. new doc：是否有漏搬/搬錯/壞掉的內容
- [ ] N
- [x] Y，漏搬、搬錯或內容壞掉，請直接調整

> 若負責部分包含以下文件，請確認兩篇內容一致，漏搬的請協助補上 (en 同)：
> 1. 高速檔案系統
> https://man.twcc.vip/docs/ccs/user-guides/storage/hfs_intro
> https://man.twcc.vip/docs/hfs/intro
> 2. 雲端物件儲存
> https://man.twcc.vip/docs/ccs/user-guides/storage/cos_intro
> https://man.twcc.vip/docs/cos/intro
> 3. 架設安全、可負載高流量的網站     https://man.twcc.vip/docs/vcs/tutorials/secure-web-high-traffic
> https://man.twcc.vip/docs/vcs_secure_web_high_traffic/intro
> 4. 使用一台虛擬運算個體架設多個且安全的網站https://man.twcc.vip/docs/vcs/tutorials/host-secured-multi-web
> https://man.twcc.vip/docs/vcs_host_secured_multi_web/intro
> 5. Module 與可用軟體套件
> https://man.twcc.vip/docs/hpc_cli/user-guides/modules/module-intro
> https://man.twcc.vip/docs/hpc_cli_module/intro

### 4. 檢查格式是否皆按[修改紀錄方式](https://man.twcc.ai/@TWSC/HJPsR7Rn9) 調整

- [x] N，不符的地方，請直接調整
- [ ] Y

> 注意：
> - admonition 無 WARNING、DANGER
> - tab 暫先限用於廣泛使用區別的 portal & CLI 

### 5. 操作看看 new doc (點連結/切換黑暗)，檢查是否有體驗不佳的呈現、連結 (side bar)

- [x] N
- [ ] Y，請先開 issue，確認後再改善調整 :pray: 

> 例如：
> - 黑暗模式下哪些圖變很醜 (同樣的問題兩位可以整合在同一個 issue)

**Comment by Oysteranpu** [comment]
[HPC 高速運算任務](https://man.twcc.ai/@twccdocs/HyVzTSOpN?type=view)、[任務型容器](https://man.twcc.ai/@twccdocs/HyMqnHupV?type=view)非 zh 結尾

**Comment by Oysteranpu** [comment]
[HPC 高速運算任務](https://man.twcc.ai/@twccdocs/HyVzTSOpN?type=view)中有一塊的result很長
沒辦法用截圖的方式將code & result 分離
![image](https://user-images.githubusercontent.com/109254397/184201095-e19844bc-b45f-4b76-8705-ac3d6ce7272b.png)

改用div黑底的方式包起來的話很醜:(
![image](https://user-images.githubusercontent.com/109254397/184201524-1457ca08-4350-43d7-8cbe-817c7d347e6f.png)

**Comment by VigaWei** [comment]
收到! 昨天我們討論是 [code & result 分離](https://man.twcc.ai/@TWSC/HJPsR7Rn9#code-amp-result-%E5%88%86%E9%9B%A2)：
- code 用 code block 包
- result 用 截圖代替 (不用自己 cmd run code 截 result > 直接截 code block 的 result，截圖可以先上傳至 man.twcc.ai 產生圖片網址)

但這個例子比較特別，橫向的資訊很長，無法一次截圖... Michelle 的方式我覺得 OK，先暫用 code block 包 result!

> 以上已加註到搬家紀錄： [code & result 分離](https://man.twcc.ai/@TWSC/HJPsR7Rn9#code-amp-result-%E5%88%86%E9%9B%A2)

另外補充，我忘記把 code 前方不用再加 「$」加入 [搬家紀錄](https://man.twcc.ai/@TWSC/HJPsR7Rn9#%E5%88%AA%E9%99%A4-code-%E5%89%8D%E7%9A%84-)，再請幫忙掃一下負責的文件，有的話請幫忙刪除 :pray:  🙇 


Hi @chuchun211, 也請看看上方的說明~~謝謝

**Comment by VigaWei** [comment]
> [HPC 高速運算任務](https://man.twcc.ai/@twccdocs/HyVzTSOpN?type=view)、[任務型容器](https://man.twcc.ai/@twccdocs/HyMqnHupV?type=view)非 zh 結尾

Thank you! 加上了! 點開後請刪除 `?type=view#標題` 就是 zh 的網址~ 🤟

**Comment by Oysteranpu** [comment]
[HPC 高速運算任務](https://man.twcc.ai/@twccdocs/HyVzTSOpN?type=view) 的**連線登入節點**中有一處有點難將 code & result 分離
目前照搬原本可複製的`div` 但同 #165 中問題相同 有點奇怪
![image](https://user-images.githubusercontent.com/109254397/184526405-bdd38696-75e1-4190-9eca-1085901cf6e9.png)

**Comment by VigaWei** [comment]
> [HPC 高速運算任務](https://man.twcc.ai/@twccdocs/HyVzTSOpN?type=view) 的**連線登入節點**中有一處有點難將 code & result 分離 目前照搬原本可複製的`div` 但同 #165 中問題相同 有點奇怪 ![image](https://user-images.githubusercontent.com/109254397/184526405-bdd38696-75e1-4190-9eca-1085901cf6e9.png)

Thank you!

想到可以直接用 code 包 `sinfo-V` (忽略掉 username)

Result 直接截 
> 
![image](https://user-images.githubusercontent.com/46370453/184616633-9ed85f25-b638-40c4-9102-a16c0c52db8f.png)

就文件像下方其他指令呈現一樣，還會有什麼疑慮嗎@@?

**Comment by Oysteranpu** [comment]
> > [HPC 高速運算任務](https://man.twcc.ai/@twccdocs/HyVzTSOpN?type=view) 的**連線登入節點**中有一處有點難將 code & result 分離 目前照搬原本可複製的`div` 但同 #165 中問題相同 有點奇怪 ![image](https://user-images.githubusercontent.com/109254397/184526405-bdd38696-75e1-4190-9eca-1085901cf6e9.png)
> 
> Thank you!
> 
> 想到可以直接用 code 包 `sinfo-V` (忽略掉 username)
> 
> Result 直接截
> 
> > 
> 
> ![image](https://user-images.githubusercontent.com/46370453/184616633-9ed85f25-b638-40c4-9102-a16c0c52db8f.png)
> 
> 就文件像下方其他指令呈現一樣，還會有什麼疑慮嗎@@?

應該沒問題! 我先按照這個方式改 ~
