### ISSUE TITLE
[中文對齊] 高速檔案系統

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#212]
> lang
> - [x] zh-Hant 
> - [ ] En

## Source docs

- zh: https://github.com/twcc/man-vip/issues/31 (檢視 Docusaurus 上的這些文件)
> 遇到還沒 merge 最新的內容，請先拉已開 PR 的檔案複製來改，若後續 merge 有衝突再解

## Target folders and files

如上述，也可直接參考 https://man.twcc.vip 上的內容：
- zh 路徑：`https://man.twcc.vip/` 之後的內容就是檔案路徑

### 1. 因搬家過程中 HackMD 也有異動，請確認此 issue 是否包含以下文件：
- [x] N 
- [ ] Y，請將該篇打勾，並檢視 HackMD 最新一筆更新紀錄、更新差異至 Dcsrs
    - [ ] [TWCC 角色權限比較：聯網與資安服務](https://man.twcc.ai/@twccdocs/role-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Frole-netndsec-zh)
    - [ ] [註冊 TWS / TWCC 帳號](https://man.twcc.ai/@twsdocs/guide-service-signup-zh)
    - [ ] [HowTo：進入會員中心？](https://man.twcc.ai/@twsdocs/howto-service-access-service-zh)
    - [ ] [FAQ-產品概觀](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-product-zh)
    - [ ] [FAQ-CFS](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-cfs-zh)
    - [ ] [CCS-容器映像檔-Matlab (BYOL)](https://man.twcc.ai/@twccdocs/ccs-concept-image-main-zh/%2F%40twccdocs%2Fccs-concept-image-matlab-zh)
    - [ ] [COS-建立刪除儲存體](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fguide-cos-create-delete-bucket-zh)
    - [ ] [VCS-監控個體](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-guide-monitor-instance-zh)
    - [ ] [VCS-彈性 IP](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-vcs-eip-zh)
    - [ ] [HowTo：建立 TWNIA2 容器](https://man.twcc.ai/@twccdocs/doc-twnia2-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-twnia2-create-sglrt-container-zh)

### 2. 請確認此 issue 是否包含 [need-to-update](https://github.com/twcc/man-vip/issues?q=is%3Aissue+is%3Aopen+label%3Aneed-to-update) 項目：
- [ ] Y，請更新文字、截圖 (連結問題可先略)
- [x] N 

### 3. 請按照手冊說明的流程，操作介面，是否發現手冊與介面之間有落差? 或是按照手冊無法操作完成?
- [x] Y，請更新文字、截圖 (連結問題可先略)
- [ ] N 

Note:
- 主要檢視項目：在 UI/CLI 使用流程上，在截圖 & 說明是否已過時或有誤
- 無法按照操作的內容 (描述性的介紹)，可以抓是否有錯字
- 若內容需大幅度的更新，請先通知 Viga 確認
- 連結先不處理
- 建基礎虛擬防火牆請小心，虛擬網路請使用 `vigatrustnetwork` (勿使用 default_network 或其他別人建立的網路)

**Comment by Oysteranpu** [comment]
[從零開始- step 2 調整 HFS 容量](https://man.twcc.ai/@twccdocs/getstarted-hfs-adjust-connec-zh#%E3%80%90%E5%BE%9E%E9%9B%B6%E9%96%8B%E5%A7%8B-TWCC%E3%80%91%E8%AA%BF%E6%95%B4-HFS-%E5%AE%B9%E9%87%8F%E4%B8%A6%E9%80%A3%E7%B7%9A%E5%82%B3%E8%BC%B8%E7%AF%80%E9%BB%9E)圖中的4.5點為科技部計畫(MST)成員
![image](https://user-images.githubusercontent.com/109254397/185352406-35cf94ac-66f3-43b0-916c-2e845b8c857b.png)

現為國科會計畫(MST)成員，已將圖片替換
![](https://cos.twcc.ai/SYS-MANUAL/uploads/upload_251040b4564754bc5913ebab456a2af8.png)

**Comment by Oysteranpu** [comment]
[查看儲存空間使用容量](https://man.twcc.vip/docs/hfs/user-guides/check-storage-usage) 中的圖片
![image](https://user-images.githubusercontent.com/109254397/185356105-06641c78-8c4a-423f-98b3-02b9e2b56b33.png)

與現況稍有不同，已將圖片替換
![](https://cos.twcc.ai/SYS-MANUAL/uploads/upload_44070f53bf2890d63fa5b94fe64dc81e.png)

**Comment by VigaWei** [comment]
### 4. 以下幾篇文件 HackMD 也有更新，請確認此 issue 是否包含以下文件：

- [ ] N 
- [ ] Y，請將該篇打勾，並檢視 HackMD 最新一筆更新紀錄、更新差異至 Dcsrs  (請在 8/19 後再更新差異)
- [快速入門](https://man.twcc.ai/@twccdocs/By1rH2oaV)
- [任務型容器](https://man.twcc.ai/@twccdocs/doc-ccs-scheduled-main-zh)
- [高速運算任務](https://man.twcc.ai/@twccdocs/doc-hpc-job-main-zh)
- [虛擬運算個體映像檔](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-vds-instance-image-zh)
- [管理映像檔](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-vds-manage-instance-image-zh)
- [HowTo：調整虛擬運算個體規格](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-vcs-resize-instance-zh)

**Comment by VigaWei** [comment]
> [查看儲存空間使用容量](https://man.twcc.vip/docs/hfs/user-guides/check-storage-usage) 中的圖片 ![image](https://user-images.githubusercontent.com/109254397/185356105-06641c78-8c4a-423f-98b3-02b9e2b56b33.png)
> 
> 與現況稍有不同，已將圖片替換 ![](https://camo.githubusercontent.com/2d947a91a02080cc95e47f5e66d74199159571ebfdb6942c208e27378dd14301/68747470733a2f2f636f732e747763632e61692f5359532d4d414e55414c2f75706c6f6164732f75706c6f61645f34343037306635336266323839306436336661356239346665363464633831652e706e67)

Thank you!! 忘記說明截圖請幫忙遮蔽一些資訊：`計畫名稱`、`人名`、`計畫代碼`，可以直接改用這張：

![](https://cos.twcc.ai/SYS-MANUAL/uploads/upload_5fdd7e5c2da81de6f3807a83208c580d.png)

/cc @chuchun211

**Comment by VigaWei** [comment]
> [從零開始- step 2 調整 HFS 容量](https://man.twcc.ai/@twccdocs/getstarted-hfs-adjust-connec-zh#%E3%80%90%E5%BE%9E%E9%9B%B6%E9%96%8B%E5%A7%8B-TWCC%E3%80%91%E8%AA%BF%E6%95%B4-HFS-%E5%AE%B9%E9%87%8F%E4%B8%A6%E9%80%A3%E7%B7%9A%E5%82%B3%E8%BC%B8%E7%AF%80%E9%BB%9E)圖中的4.5點為科技部計畫(MST)成員 ![image](https://user-images.githubusercontent.com/109254397/185352406-35cf94ac-66f3-43b0-916c-2e845b8c857b.png)
> 
> 現為國科會計畫(MST)成員，已將圖片替換 ![](https://camo.githubusercontent.com/764984196f5532f9474a5ee40b6db0ed8ab820b483788d64fe17a4b5762ef68a/68747470733a2f2f636f732e747763632e61692f5359532d4d414e55414c2f75706c6f6164732f75706c6f61645f32353130343062343536343735346263353931336562616234353661326166382e706e67)

Hi Michelle~ 

請幫忙置換成以下這張圖，有把主機帳號 & 計畫代號名稱遮蔽~ 感謝 🙏 

```
![](https://cos.twcc.ai/SYS-MANUAL/uploads/upload_e3b883228620b3320df74a4970bbcfcc.png)

```

✋  截圖需遮蔽的資訊我記錄在 [here](https://man.twcc.ai/@TWSC/rkpK132C5/https%3A%2F%2Fman.twcc.ai%2F%40TWSC%2FBJxw2ohAq) ✋ ，以下需遮蔽的項目請協助注意
> ![image](https://user-images.githubusercontent.com/46370453/185559486-57325a14-950c-4441-a0b9-31240602d770.png)

/cc @chuchun211

**Comment by Oysteranpu** [comment]
[從零開始-step 2-Enterprise](https://man.twcc.vip/docs/hfs/get-started)將傳案名稱遮蔽

![image](https://user-images.githubusercontent.com/109254397/185799471-724d9cdb-9b0b-4c15-aa09-4598694749f4.png)

**Comment by Oysteranpu** [comment]
[查看儲存空間使用容量](https://man.twcc.vip/docs/hfs/user-guides/check-storage-usage)將專案名稱遮蔽

![image](https://user-images.githubusercontent.com/109254397/185799649-f7318b91-4049-4cad-986b-fa317419e4f4.png)
