### ISSUE TITLE
[中文對齊] 台灣杉二號 (命令列介面) -4

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#222]
> lang
> - [x] zh-Hant 
> - [ ] En

## Source docs

- zh: https://github.com/twcc/man-vip/issues/105 (檢視 Docusaurus 上的這些文件) ( 🌷  **MPI 三份可略** 🌷)
> 遇到還沒 merge 最新的內容，請先拉已開 PR 的檔案複製來改，若後續 merge 有衝突再解

## Target folders and files

如上述，也可直接參考 https://man.twcc.vip 上的內容：
- zh 路徑：`https://man.twcc.vip/` 之後的內容就是檔案路徑

### 1. 因搬家過程中 HackMD 也有異動，請確認此 issue 是否包含以下文件：
- [ ] N 
- [x] Y，請將該篇打勾，並檢視 HackMD 最新一筆更新紀錄、更新差異至 Dcsrs
    - [ ] [TWCC 角色權限比較：聯網與資安服務](https://man.twcc.ai/@twccdocs/role-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Frole-netndsec-zh)
    - [ ] [註冊 TWS / TWCC 帳號](https://man.twcc.ai/@twsdocs/guide-service-signup-zh)
    - [ ] [HowTo：進入會員中心？](https://man.twcc.ai/@twsdocs/howto-service-access-service-zh)
    - [ ] [FAQ-產品概觀](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-product-zh)
    - [ ] [FAQ-CFS](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-cfs-zh)
    - [ ] [CCS-容器映像檔-Matlab (BYOL)](https://man.twcc.ai/@twccdocs/ccs-concept-image-main-zh/%2F%40twccdocs%2Fccs-concept-image-matlab-zh)
    - [ ] [COS-建立刪除儲存體](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fguide-cos-create-delete-bucket-zh)
    - [ ] [VCS-監控個體](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-guide-monitor-instance-zh)
    - [ ] [VCS-彈性 IP](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-vcs-eip-zh)
    - [x] [HowTo：建立 TWNIA2 容器](https://man.twcc.ai/@twccdocs/doc-twnia2-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-twnia2-create-sglrt-container-zh)

### 2. 請確認此 issue 是否包含 [need-to-update](https://github.com/twcc/man-vip/issues?q=is%3Aissue+is%3Aopen+label%3Aneed-to-update) 項目：
- [ ] Y，請更新文字、截圖 (連結問題可先略)
- [x] N 

### 3. 請按照手冊說明的流程，操作介面，是否發現手冊與介面之間有落差? 或是按照手冊無法操作完成?
- [ ] Y，請更新文字、截圖 (連結問題可先略)
- [x] N 

Note:
- 主要檢視項目：在 UI/CLI 使用流程上，在截圖 & 說明是否已過時或有誤
- 無法按照操作的內容 (描述性的介紹)，可以抓是否有錯字
- 若內容需大幅度的更新，請先通知 Viga 確認
- 連結先不處理
- 建基礎虛擬防火牆請小心，虛擬網路請使用 `vigatrustnetwork` (勿使用 default_network 或其他別人建立的網路)

**Comment by VigaWei** [comment]
### 4. 以下幾篇文件 HackMD 也有更新，請確認此 issue 是否包含以下文件：

- [ ] N 
- [ ] Y，請將該篇打勾，並檢視 HackMD 最新一筆更新紀錄、更新差異至 Dcsrs  (請在 8/19 後再更新差異)
- [快速入門](https://man.twcc.ai/@twccdocs/By1rH2oaV)
- [任務型容器](https://man.twcc.ai/@twccdocs/doc-ccs-scheduled-main-zh)
- [高速運算任務](https://man.twcc.ai/@twccdocs/doc-hpc-job-main-zh)
- [虛擬運算個體映像檔](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-vds-instance-image-zh)
- [管理映像檔](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-vds-manage-instance-image-zh)
- [HowTo：調整虛擬運算個體規格](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-vcs-resize-instance-zh)

**Comment by VigaWei** [comment]
有些卡關再請 @chuchun211 update

**Comment by chuchun211** [comment]
[建立 TWNIA2 容器 - TWCC 預載的容器映像檔](https://man.twcc.vip/docs/hpc_cli/tutorials/create-twnia2-containers/#1-twcc-%E9%A0%90%E8%BC%89%E7%9A%84%E5%AE%B9%E5%99%A8%E6%98%A0%E5%83%8F%E6%AA%94)
不太確定如何使用...
![image](https://user-images.githubusercontent.com/67446293/186567785-08b32fe8-27a4-473a-b507-bdc84d243627.png)

**Comment by chuchun211** [comment]
[容器跨節點高速運算－AI Benchmark - Step 5. 提交 Job](http://localhost:3000/docs/hpc_cli/tutorials/ai-benchmark-container#step-5-%E6%8F%90%E4%BA%A4-job)
我不知道我有沒有獲得小白能了解該怎麼使用的資訊...
![image](https://user-images.githubusercontent.com/67446293/186588034-b24854dc-6857-4c76-8620-3d0e8fbce45e.png)
![image](https://user-images.githubusercontent.com/67446293/186590439-11fc470d-9a02-4ce5-8712-0bd2df06f952.png)

**Comment by chuchun211** [comment]
[使用 Conda 管理套件與執行 Job - 載入 Conda 並建立虛擬環境](https://man.twcc.vip/docs/hpc_cli/tutorials/conda-manage-package-and-submit-job#step-1-%E8%BC%89%E5%85%A5-conda-%E4%B8%A6%E5%BB%BA%E7%AB%8B%E8%99%9B%E6%93%AC%E7%92%B0%E5%A2%83)
![image](https://user-images.githubusercontent.com/67446293/186592965-df5eccfc-0081-4042-93c9-284c4e843ba4.png)

**Comment by chuchun211** [comment]
TODO1列的[HowTo：建立 TWNIA2 容器](https://man.twcc.ai/@twccdocs/doc-twnia2-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-twnia2-create-sglrt-container-zh)和現在搬完的文件沒有差異

**Comment by VigaWei** [comment]
> [容器跨節點高速運算－AI Benchmark - Step 5. 提交 Job](https://man.twcc.vip/docs/hpc_cli/tutorials/ai-benchmark-container/#step-5-%E6%8F%90%E4%BA%A4-job) 我不知道我有沒有獲得小白能了解該怎麼使用的資訊... ![image](https://user-images.githubusercontent.com/67446293/186588034-b24854dc-6857-4c76-8620-3d0e8fbce45e.png) ![image](https://user-images.githubusercontent.com/67446293/186590439-11fc470d-9a02-4ce5-8712-0bd2df06f952.png)

沒有獲得是文件要改善一下 ✏️ ✏️

**Comment by VigaWei** [comment]
需要花時間測試和改寫，先記錄到內部 Gitlab: https://git.twcc.ai/twcc/manual/-/issues/371，
這幾篇可以先完成卡關以前的部分~ 謝謝!!

**Comment by chuchun211** [comment]
> 需要花時間測試和改寫，先記錄到內部 Gitlab: [https://git.twcc.ai/twcc/manual/-/issues/371，](https://git.twcc.ai/twcc/manual/-/issues/371%EF%BC%8C) 這幾篇可以先完成卡關以前的部分~ 謝謝!!

卡關以前沒有問題～
加上TODO1其實不需要搬所以目前沒有需要更動！
