### ISSUE TITLE
[中文搬家調整2+建檔] 高速檔案系統

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#293]
> lang
> - [x] zh-Hant 
> - [ ] En

## Source docs

- zh: https://github.com/twcc/man-vip/issues/31 (檢視 [Docusaurus](https://man.twcc.vip) 上的這些文件)

## Target folders and files

如上述，也可直接參考 https://man.twcc.vip 上的內容：
- zh 路徑：`https://man.twcc.vip/` 之後的內容就是檔案路徑

> 路徑有調整~請抓 tws-sync 最新的內容 :pray: 

### 1. 依 Docusaurus 路徑調整連結

> ![](https://i.imgur.com/wQUk8ja.png)

範例：[Staging-連線容器](https://staging.twcc.vip/docs/ccs-interactive-container/user-guides/create-connect/connect-container
)

Ref：https://docusaurus.io/docs/markdown-features/links

### 2. 請確認此 issue 是否包含 [need-to-update](https://github.com/twcc/man-vip/issues?q=is%3Aissue+is%3Aopen+label%3Aneed-to-update) `連結調整` 項目：
- [ ] Y，請協助更新為合適的連結
- [x] N 

### 3. 請確認此 issue 是否包含無操作說明的 TWCC CLI (tab)：
- [ ] Y，請將 tab name 改為 `TWCC CLI (TBD)`，如下圖：
> ![](https://i.imgur.com/QQthgr7.png)

- [x] N 

### 4. 請將文件資訊填入 Google sheet

- Google sheet：[文件列表](https://docs.google.com/spreadsheets/d/1hRYHhSVegSOhTNxgwIm7n9wNBXZ1h7EUUgZ5B-ODTxw/edit#gid=0)

**Comment by Oysteranpu** [comment]
[調整 HFS 容量並連線傳輸節點-step Academic](https://man.twcc.vip/docs/hfs/get-started#step-1-%E6%BA%96%E5%82%99%E5%B7%A5%E4%BD%9C%E5%B8%B3%E8%99%9F%E8%A8%88%E7%95%AB%E5%B0%88%E6%A1%88%E9%A1%8D%E5%BA%A6)中的**購買計畫額度**
目前指向另一篇文件[購買計畫額度](https://man.twcc.ai/@twccdocs/doc-service-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2FS17dwAja4%3Ftype%3Dview)(for TWCC)
與一開始搬家的文件(for TWS)有所不同
![image](https://user-images.githubusercontent.com/109254397/189500235-b16764c4-698d-49ec-90cf-cf75ffb34122.png)

且兩篇的內容不一樣
- for TWS
![image](https://user-images.githubusercontent.com/109254397/189500481-6d90c3ab-260a-4f33-92b2-1da0e1cce10d.png)

- for TWCC
![image](https://user-images.githubusercontent.com/109254397/189500493-cc452f0a-c8f9-4704-9da9-aaadbbf06cb3.png)


想問連結是要指向目前小恐龍中的[申請專案與額度](https://man.twcc.vip/docs/member/user-guides/billing/apply-credits)(for TWS)嗎~
(但又感覺很怪，小恐龍比較像是在針對TWCC教學)

**Comment by Oysteranpu** [comment]
[調整 HFS 容量並連線傳輸節點-step Academic](https://man.twcc.vip/docs/hfs/get-started#step-1-%E6%BA%96%E5%82%99%E5%B7%A5%E4%BD%9C%E5%B8%B3%E8%99%9F%E8%A8%88%E7%95%AB%E5%B0%88%E6%A1%88%E9%A1%8D%E5%BA%A6)中的**計畫錢包管理**
目前指向另一篇文件[計畫錢包管理](https://man.twcc.ai/@twccdocs/doc-service-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-service-manage-project-wallet-zh)(for TWCC)
![image](https://user-images.githubusercontent.com/109254397/189500605-34a1612e-790f-4116-b398-2e0e0ea209f0.png)

小恐龍內(for TWS)沒有這篇

**Comment by Oysteranpu** [comment]
[調整 HFS 容量並連線傳輸節點-step 2](https://man.twcc.ai/@twccdocs/doc-service-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-service-view-billing-resource-usage-zh)info第二點中的**Academic**
目前指向另一篇文件[檢視額度與資源用量](https://man.twcc.ai/@twccdocs/doc-service-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-service-view-billing-resource-usage-zh)(for TWCC)
![image](https://user-images.githubusercontent.com/109254397/189500901-6dab2f07-12bd-4818-898d-03e244dc2dab.png)

小恐龍內(for TWS)沒有這篇

**Comment by Oysteranpu** [comment]
[調整 HFS 容量並連線傳輸節點](https://man.twcc.vip/docs/hfs/get-started#%E7%9B%B8%E9%97%9C-faq)相關 FAQ中的**高速檔案系統 (HFS)**
目前指向HFS的[服務概觀](https://man.twcc.ai/@twccdocs/doc-hfs-main-zh)
覺得應該要指向[TWCC FAQs | 高速檔案系統 (HFS)](https://man.twcc.vip/docs/faq/storage/hfs)更好~(已更改)
![image](https://user-images.githubusercontent.com/109254397/189500968-5f1a922e-ce9f-4dfd-bf8a-df817fa480d5.png)

**Comment by Oysteranpu** [comment]
問題同 #304
