### ISSUE TITLE
[中文搬家] 雲端物件儲存

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#30]
### Source docs
- [全*10](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fcos-overview-zh)

> ![image](https://user-images.githubusercontent.com/46370453/180106679-dfdd961e-45df-4c26-99c6-a7c0fee68aa9.png)

### Target folders and files
- `docs\cos`

### To-do
- refer to PPT [p.24 to p.36](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.p67)

**Comment by VigaWei** [comment]
@VigaWei Study: copy code

**Comment by VigaWei** [comment]
- Michelle Est: 1.5 hr
- Joy Est: 1.5 hr

**Comment by Oysteranpu** [comment]
所有有style都要注意更改語法格式
不然會造成頁面當機
![image](https://user-images.githubusercontent.com/109254397/180602353-90a1f7e6-937f-4fc9-81a3-fc7322a4b441.png)
![image](https://user-images.githubusercontent.com/109254397/180602401-09d05a17-faa4-4aea-bbd1-b0e5ce7c59e0.png)

**修更為`style={{height:25+'px'}}`即可解決**

**Comment by Oysteranpu** [comment]
【OLD】[雲端物件儲存-檔案加密](https://man.twcc.ai/@twccdocs/guide-cos-encryption-zh#%E6%AA%94%E6%A1%88%E5%8A%A0%E5%AF%86)
第三方軟體：S3 browser`<details>`最後缺少`</details>`造成小恐龍錯誤
但在【OLD】可以正常運作
加上`</details>`即可解決
![image](https://user-images.githubusercontent.com/109254397/180620675-7db9f06f-38fb-467e-b350-fa2f10d976dd.png)

**Comment by Oysteranpu** [comment]
`<span class = "number">&#10102;</span>`
無法與要粗體的文字一起出現，會造成語法錯誤
目前的解法：直接將<span class = "number">&#10102;</span>貼上不用class呈現
![image](https://user-images.githubusercontent.com/109254397/180621237-1e562e36-fc36-4102-b40a-63a20a9e397e.png)
![image](https://user-images.githubusercontent.com/109254397/180621227-a05aad99-b5b4-4961-a9f1-0542d56535f1.png)

**Comment by VigaWei** [comment]
Thanks! 請參考[ p.35](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.g13e96fe42dd_0_117) 發 PR
