### ISSUE TITLE
[中文搬家調整2+建檔] FAQ

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#302]
> lang
> - [x] zh-Hant 
> - [ ] En

## Source docs

- zh: https://github.com/twcc/man-vip/issues/77 (檢視 [Docusaurus](https://man.twcc.vip) 上的這些文件)

## Target folders and files

如上述，也可直接參考 https://man.twcc.vip 上的內容：
- zh 路徑：`https://man.twcc.vip/` 之後的內容就是檔案路徑

> 路徑有調整~請抓 tws-sync 最新的內容 :pray: 

### 1. 依 Docusaurus 路徑調整連結

> ![](https://i.imgur.com/wQUk8ja.png)

範例：[Staging-連線容器](https://staging.twcc.vip/docs/ccs-interactive-container/user-guides/create-connect/connect-container
)

Ref：https://docusaurus.io/docs/markdown-features/links

### 2. 請確認此 issue 是否包含 [need-to-update](https://github.com/twcc/man-vip/issues?q=is%3Aissue+is%3Aopen+label%3Aneed-to-update) `連結調整` 項目：
- [x] Y，請協助更新為合適的連結
- [ ] N 

### 3. 請確認此 issue 是否包含無操作說明的 TWCC CLI (tab)：
- [ ] Y，請將 tab name 改為 `TWCC CLI (TBD)`，如下圖：
> ![](https://i.imgur.com/QQthgr7.png)

- [x] N 

### 4. 請將文件資訊填入 Google sheet

- Google sheet：[文件列表](https://docs.google.com/spreadsheets/d/1hRYHhSVegSOhTNxgwIm7n9wNBXZ1h7EUUgZ5B-ODTxw/edit#gid=0)

**Comment by Oysteranpu** [comment]
12天前新增了[TWCC FAQs | OneAI](https://man.twcc.ai/@twccdocs/faq-oneai-zh#TWCC-FAQs--OneAI)這一頁，小恐龍內沒有

[TWCC FAQs | 虛擬運算服務 (VCS)](https://man.twcc.ai/@twccdocs/faq-vcs-zh#TWCC-FAQs--%E8%99%9B%E6%93%AC%E9%81%8B%E7%AE%97%E6%9C%8D%E5%8B%99-VCS)在12天前更新了
小恐龍會一起更新~

**Comment by Oysteranpu** [comment]
![image](https://user-images.githubusercontent.com/109254397/190001583-7e75a0b5-98f6-4522-bcdc-b566bf825fc9.png)
[TWCC FAQs | 容器運算服務 (CCS)-儲存與資料傳輸Q10](https://man.twcc.vip/docs/faq/compute/ccs#%E5%84%B2%E5%AD%98%E8%88%87%E8%B3%87%E6%96%99%E5%82%B3%E8%BC%B8)中的[安裝 TWCC CLI](https://man.twcc.ai/@twccdocs/doc-cli-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-cli-install-linux-zh)
小恐龍內沒有，目前維持原本的連結~

**Comment by VigaWei** [comment]
> 12天前新增了[TWCC FAQs | OneAI](https://man.twcc.ai/@twccdocs/faq-oneai-zh#TWCC-FAQs--OneAI)這一頁，小恐龍內沒有
> 
> [TWCC FAQs | 虛擬運算服務 (VCS)](https://man.twcc.ai/@twccdocs/faq-vcs-zh#TWCC-FAQs--%E8%99%9B%E6%93%AC%E9%81%8B%E7%AE%97%E6%9C%8D%E5%8B%99-VCS)在12天前更新了 小恐龍會一起更新~

辛苦了~~ 感謝幫注意!! 我們先處理先階段的搬家就可以~~ 告一段落後我再開單請你們協助這段時間 HackMD 又更新的部分 🙏

**Comment by VigaWei** [comment]
> ![image](https://user-images.githubusercontent.com/109254397/190001583-7e75a0b5-98f6-4522-bcdc-b566bf825fc9.png) [TWCC FAQs | 容器運算服務 (CCS)-儲存與資料傳輸Q10](https://man.twcc.vip/docs/faq/compute/ccs#%E5%84%B2%E5%AD%98%E8%88%87%E8%B3%87%E6%96%99%E5%82%B3%E8%BC%B8)中的[安裝 TWCC CLI](https://man.twcc.ai/@twccdocs/doc-cli-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-cli-install-linux-zh) 小恐龍內沒有，目前維持原本的連結~

謝謝! 先請如 https://github.com/twcc/man-vip/issues/326 這題的作法，先協助導至 CLI GitHub

**Comment by Oysteranpu** [comment]
[TWCC FAQs | 虛擬運算服務 (VCS) - 儲存與資料傳輸 - Q2 & Q5](https://man.twcc.vip/docs/faq/compute/vcs#%E5%84%B2%E5%AD%98%E8%88%87%E8%B3%87%E6%96%99%E5%82%B3%E8%BC%B8)
這兩處目前一樣如 https://github.com/twcc/man-vip/issues/326 這題的作法，先導至 CLI GitHub
但感覺文件內敘述要修改
![image](https://user-images.githubusercontent.com/109254397/190238314-7c1225b5-e165-4aa6-89ae-52dab862b592.png)

![image](https://user-images.githubusercontent.com/109254397/190238194-c30125f4-dd50-4a46-b535-5d9ee22ebd60.png)
