### ISSUE TITLE
[中文搬家調整2+建檔] 雲端檔案服務/OneAI

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#303]
> lang
> - [x] zh-Hant 
> - [ ] En

## Source docs

- zh: https://github.com/twcc/man-vip/issues/78 (檢視 [Docusaurus](https://man.twcc.vip) 上的這些文件)

## Target folders and files

如上述，也可直接參考 https://man.twcc.vip 上的內容：
- zh 路徑：`https://man.twcc.vip/` 之後的內容就是檔案路徑

> 路徑有調整~請抓 tws-sync 最新的內容 :pray: 

### 1. 依 Docusaurus 路徑調整連結

> ![](https://i.imgur.com/wQUk8ja.png)

範例：[Staging-連線容器](https://staging.twcc.vip/docs/ccs-interactive-container/user-guides/create-connect/connect-container
)

Ref：https://docusaurus.io/docs/markdown-features/links

### 2. 請確認此 issue 是否包含 [need-to-update](https://github.com/twcc/man-vip/issues?q=is%3Aissue+is%3Aopen+label%3Aneed-to-update) `連結調整` 項目：
- [ ] Y，請協助更新為合適的連結
- [x] N 

### 3. 請確認此 issue 是否包含無操作說明的 TWCC CLI (tab)：
- [ ] Y，請將 tab name 改為 `TWCC CLI (TBD)`，如下圖：
> ![](https://i.imgur.com/QQthgr7.png)

- [ ] N 

### 4. 請將文件資訊填入 Google sheet

- Google sheet：[文件列表](https://docs.google.com/spreadsheets/d/1hRYHhSVegSOhTNxgwIm7n9wNBXZ1h7EUUgZ5B-ODTxw/edit#gid=0)

**Comment by Oysteranpu** [comment]
[熱儲存區檔案存取介面](https://man.twcc.ai/@twccdocs/guide-cfs-access-interface-mngmnt-zh#%E7%86%B1%E5%84%B2%E5%AD%98%E5%8D%80%E6%AA%94%E6%A1%88%E5%AD%98%E5%8F%96%E4%BB%8B%E9%9D%A2)9天前更新了
小恐龍會一併更新~

**Comment by Oysteranpu** [comment]
[訂閱政策](https://man.twcc.vip/docs/oneai/subscription-policies)中的國網學研界用戶
指向另外一篇[TWCC定價](https://man.twcc.ai/@twccdocs/SJWlN3YDr#%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7)
與小恐龍中的[pricing](https://man.twcc.vip/docs/pricing)內容不同
目前沒有更動
![image](https://user-images.githubusercontent.com/109254397/189525541-c640e56d-38f2-41a2-a593-7e17a296667d.png)

**Comment by Oysteranpu** [comment]
[服務概觀](https://man.twcc.vip/docs/oneai/overview)中的TWCC OneAI 提供：
皆指向另外的[OneAI 文件](https://docs.oneai.twcc.ai/s/xKNcU3O5D)
目前也沒有更動~
![image](https://user-images.githubusercontent.com/109254397/189525664-8306dfc1-77cb-4e0b-bc15-242ba469d91f.png)

**Comment by VigaWei** [comment]
> [服務概觀](https://man.twcc.vip/docs/oneai/overview)中的TWCC OneAI 提供： 皆指向另外的[OneAI 文件](https://docs.oneai.twcc.ai/s/xKNcU3O5D) 目前也沒有更動~ ![image](https://user-images.githubusercontent.com/109254397/189525664-8306dfc1-77cb-4e0b-bc15-242ba469d91f.png)
> 
> [AI Maker](https://man.twcc.vip/docs/oneai/user-guides/features)也是~ ![image](https://user-images.githubusercontent.com/109254397/189525761-892d0d9f-ab07-4648-bc53-80d02cf13c3f.png)

沒問題，謝謝! OneAI 操作手冊目前是其他團隊維運，還沒有搬到 TWCC HackMD，請先連回原本的連結即可
