### ISSUE TITLE
[中文搬家] 高速檔案系統

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#31]
### Source docs
- [全*7](https://man.twcc.ai/@twccdocs/doc-hfs-main-zh/%2F%40twccdocs%2Fhfs-overview-zh)
> ![image](https://user-images.githubusercontent.com/46370453/180106742-c9337738-500a-499f-a34a-dce4457bed17.png)

### Target folders and files
- `docs\hfs`

### To-do
- refer to PPT [p.24 to p.36](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.p67)

**Comment by VigaWei** [comment]
- Michelle Est: 1 hr
- Joy Est: 1 hr

**Comment by Oysteranpu** [comment]
小恐龍表格內無法放上標語法，會造成錯誤(已確認是上標問題)
![image](https://user-images.githubusercontent.com/109254397/180663868-49178cbb-adb9-4e1f-a97c-c1cb6dba920e.png)
![image](https://user-images.githubusercontent.com/109254397/180664154-d6f267ba-df32-4c9c-a151-d7ed35bce891.png)

目前先使用Unicode的上標符號代替
![image](https://user-images.githubusercontent.com/109254397/180664236-8499af73-d855-4279-912c-d23181af34bb.png)
![image](https://user-images.githubusercontent.com/109254397/180664219-7b71d024-6ba3-4309-8c10-e8e18b06da8a.png)

**Comment by Oysteranpu** [comment]
【OLD】[高速檔案系統-檔案管理](https://man.twcc.ai/@twccdocs/doc-hfs-main-zh/%2F%40twccdocs%2Fguide-hfs-manage-files-zh)最後多一個`</div>`造成小恐龍錯誤，刪掉即可
![image](https://user-images.githubusercontent.com/109254397/180665317-c6fda867-e22b-405d-914b-9ebe91a70fac.png)

**Comment by Oysteranpu** [comment]
[高速檔案系統-空間管理政策](https://man.twcc.ai/@twccdocs/doc-hfs-main-zh/%2F%40twccdocs%2Fterms-hfs-storage-mngmt-policies-zh)表格中的✓以及✗是使用`:white_check_mark:`(emoji)
可以正常運作， [#24](https://github.com/twcc/man-vip/issues/24)表格中的✓以及✗或許可以使用這個方式替代(但有點醜)
![image](https://user-images.githubusercontent.com/109254397/180665618-f3c6e2b1-d931-4401-91ec-7336f5099f4a.png)

**Comment by Oysteranpu** [comment]
[調整 HFS 容量並連線傳輸節點](https://man.twcc.ai/@twccdocs/doc-hfs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fgetstarted-hfs-adjust-connec-zh)這一塊會大爆炸
目前是發現`style="background-color:#FF0000;border-radius: 30px;padding: 0.3em; font-size: 16px;"`這一段會有問題
可能要找一下小恐龍內的background-color、border-radius要如何呈現
有發現style內不可以有"-"出現
所以這一頁目前沒有做(爆炸太多點
![image](https://user-images.githubusercontent.com/109254397/180667309-dbaba888-227d-49f6-986c-b5db169d6695.png)

**Comment by Oysteranpu** [comment]
> [調整 HFS 容量並連線傳輸節點](https://man.twcc.ai/@twccdocs/doc-hfs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fgetstarted-hfs-adjust-connec-zh)這一塊會 發現目前正在發現會有什麼`style="background-color:#FF0000;border-radius: 30px;padding: 0.3em; font-size: 16px;"`問題 要找一下小爆炸要在裡面的背景顏色、邊界半徑如何顯示 有這個樣式裡面不可以有”-”出現 所以這一頁目前沒有做（爆炸點） ![圖片](https://user-images.githubusercontent.com/109254397/180667309-dbaba888-227d-49f6-986c-b5db169d6695.png)

更新，我改出來了٩(｡•ω•｡)و
```
<font style={{backgroundColor:'#FF0000', borderRadius:30+'px', padding:0.3+'em', fontZize:16+'px'}}>

<font style={{color:'white'}}>

<b>&nbsp;Academic&nbsp;</b>
```
將background-color等有連結號的樣式改成用大寫連在一起
在注意將顏色代碼等用'color'框起來
![image](https://user-images.githubusercontent.com/109254397/180675463-8ae3d888-c88b-4d91-a6df-0a9ff87b5339.png)

**Comment by VigaWei** [comment]
> 小恐龍表格內無法放上標語法，會造成錯誤(已確認是上標問題) ![image](https://user-images.githubusercontent.com/109254397/180663868-49178cbb-adb9-4e1f-a97c-c1cb6dba920e.png) ![image](https://user-images.githubusercontent.com/109254397/180664154-d6f267ba-df32-4c9c-a151-d7ed35bce891.png)
> 
> 目前先使用Unicode的上標符號代替 ![image](https://user-images.githubusercontent.com/109254397/180664236-8499af73-d855-4279-912c-d23181af34bb.png) ![image](https://user-images.githubusercontent.com/109254397/180664219-7b71d024-6ba3-4309-8c10-e8e18b06da8a.png)

Hi, 上標可否改成 <sup>1</sup> 試試看? 感謝 🙏

**Comment by Oysteranpu** [comment]
> Hi, 上標可否改成 `<sup>1</sup>` 試試看? 感謝 🙏

結果我在`<sup>`跟[2]的前後加空格就解決了XD 
- 修正為`<sup> [2] </sup>`

![image](https://user-images.githubusercontent.com/109254397/180932262-674049b0-4d57-41c9-860f-bfb64a35bad5.png)
