### ISSUE TITLE
[待討論] 管理容器 刪除容器偶爾發生無法刪除的狀況

### ISSUE THREAD

**Issue by Oysteranpu** [twcc/man-vip#46]
- 待待討論 文件連結：[管理容器-刪除容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-manage-zh#%E5%88%AA%E9%99%A4%E5%AE%B9%E5%99%A8)

- 目前狀況 (as is)：
刪除容器偶爾發生無法刪除的狀況
可能與啟用或關閉「刪除保護機制」延遲有關
通常稍等一下重新整理即可解決
![image](https://user-images.githubusercontent.com/109254397/179673413-2bef3455-0fb7-4e0e-929b-55347be9d43b.png)
- 理想狀況 (to be)：
應該要沒有延遲，關閉「刪除保護機制」後能馬上刪除容器

**Comment by VigaWei** [comment]
請問是建立 CCS 後，立即想刪除時無法刪除嗎? 情境還請 @Oysteranpu 協助再稍微仔細描述~~感謝

也請再試試看幾次是否會踩到 :pray:

**Comment by Oysteranpu** [comment]
> 請問是建立 CCS 後，立即想刪除時無法刪除嗎? 情境還請 @Oysteranpu 協助再稍微仔細描述~~感謝
> 
> 也請再試試看幾次是否會踩到 🙏

有嘗試過幾次，都是發生在原本有 _**啟用**_ 「刪除保護機制」時，改為 _**關閉**_ 後發生立即想刪除時無法刪除
刷新介面可以解決此問題，可能與網頁延遲有關

**Comment by VigaWei** [comment]
> > 請問是建立 CCS 後，立即想刪除時無法刪除嗎? 情境還請 @Oysteranpu 協助再稍微仔細描述~~感謝
> > 也請再試試看幾次是否會踩到 🙏
> 
> 有嘗試過幾次，都是發生在原本有 _**啟用**_ 「刪除保護機制」時，改為 _**關閉**_ 後發生立即想刪除時無法刪除 刷新介面可以解決此問題，可能與網頁延遲有關

感謝~ 已轉至內部 Gitlab 討論 & 追蹤：https://git.twcc.ai/twcc/UIUX/-/issues/954

**Comment by VigaWei** [comment]
今天操作關閉 保護機制 後 > 回到管理頁，可以刪除~ @Oysteranpu 的流程也是這樣嗎? 可以明天一起操作看看~

![protection-deletion](https://user-images.githubusercontent.com/46370453/182557244-acf8bb6b-2fa4-46b1-bf4d-c0968a3bd493.gif)

**Comment by VigaWei** [comment]
> > 今天操作關閉 保護機制 後 > 回到管理頁，可以刪除~ @Oysteranpu 的流程也是這樣嗎? 可以明天一起操作看看~
> 
> 剛剛操作了一次是正常的可以馬上刪除 感覺是跟網路延遲有關，很偶爾發生QQ

若有發生再幫忙螢幕錄影回報~~感謝!!

**Comment by VigaWei** [comment]
先關閉，若有發生再重開追蹤~ 🙏
