### ISSUE TITLE
[待調整] 雲端物件儲存 介面和文件不一致-1

### ISSUE THREAD

**Issue by Oysteranpu** [twcc/man-vip#47]
- 待調整/待討論 文件連結：[雲端物件儲存-建立刪除儲存體](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fguide-cos-create-delete-bucket-zh)

- 目前狀況 (as is)：
HackMD目前的圖如下：
![image](https://user-images.githubusercontent.com/109254397/179721718-d4879cbb-29a6-49e6-9d53-fcac991700bd.png)

- 理想狀況 (to be)：
實際操作左側列表稍有不同，應更新圖片
![image](https://user-images.githubusercontent.com/109254397/179722611-7b4194bc-12f6-4b8b-9657-e7bd35808f41.png)

**Comment by VigaWei** [comment]
確認已更新! 謝謝

![image](https://user-images.githubusercontent.com/46370453/188111218-3ca1cd47-2529-4c9e-a8e5-2563132e2963.png)
