### ISSUE TITLE
[待調整] 雲端物件儲存 介面和文件不一致-2

### ISSUE THREAD

**Issue by Oysteranpu** [twcc/man-vip#48]
- 待調整/待討論 文件連結：[雲端物件儲存-檢視、搜尋、刪除檔案](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fguide-cos-view-search-delete-files-zh)

- 目前狀況 (as is)：
在搜尋檔案的部分HackMD中的圖有"進階METADATA搜尋"
![image](https://user-images.githubusercontent.com/109254397/179724218-726eaaf6-82f0-4f87-b2f4-d426d945e9f2.png)
- 理想狀況 (to be)：
實際操作則沒有，應更新圖片
![image](https://user-images.githubusercontent.com/109254397/179725193-5a7fed8c-99fd-42d9-999c-2d140b47aa13.png)

**Comment by VigaWei** [comment]
確認已更新! 謝謝
![image](https://user-images.githubusercontent.com/46370453/188111506-026f8350-b9e5-419a-94ce-d47ff622887d.png)
