### ISSUE TITLE
[待討論] TWCC 會員/計畫/帳務 頁面跳轉的情況不一/介面和文件不一致

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#55]
- 待調整/待討論 文件連結：[註冊帳號](https://man.twcc.ai/@twccdocs/doc-service-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-service-signup-zh#%E8%A8%BB%E5%86%8A-TWCC-%E5%B8%B3%E8%99%9F)
- 目前狀況 (as is)：
Step 1指示按下註冊後
有時候和文件中的Step 2一樣是閱讀個資及權利義務聲明
![image](https://user-images.githubusercontent.com/67446293/181016576-27b855a2-67e7-4fb7-a8d6-61ab8b5e0f59.png)
有時候會跳出[註冊 TWS / TWCC 帳號](https://man.twcc.ai/@twsdocs/doc-mber-pjct-blng-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twsdocs%2Fguide-service-signup-zh)中的Step 2. 輸入註冊帳號的信箱
但是頁面是iService而非TWS
![image](https://user-images.githubusercontent.com/67446293/179655910-c7eb5673-15b5-4fd6-b741-8906dcf4d9fd.png)
- 理想狀況 (to be)：
1. 只會跳轉到 閱讀個資及權利義務聲明
或是
2. 只會跳轉到和TWS一樣是 輸入註冊帳號的信箱 ，修改文件

**Comment by VigaWei** [comment]
確認文件：https://man.twcc.vip/docs/member/user-guides/member-key-quota/sign-up-for-twcc/ 

- [x] 內容是放 Enterprise 註冊帳號流程 (Academic 待整合 https://github.com/twcc/man-vip/issues/332)
- [x] 已確認內容與 Enterprise (https://tws.twcc.ai/) 的註冊流程一致
