### ISSUE TITLE
[待調整] 開發型容器 連結不理想-2

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#57]
- 待調整/待討論 文件連結：[HowTo：檢視運算資源概況－GPU Burn Testing](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2FByXcZRspE%3Ftype%3Dview#Step-3-%E9%80%A3%E7%B7%9A%E5%AE%B9%E5%99%A8%E3%80%81%E4%B8%8B%E8%BC%89%E8%A8%93%E7%B7%B4%E7%A8%8B%E5%BC%8F)
- 目前狀況 (as is)：
「使用Jupyter Notebook」的連結點下去會是開發型容器的服務概觀
![image](https://user-images.githubusercontent.com/67446293/179668575-b7137ba6-c192-4121-977d-dc18319e660f.png)
- 理想狀況 (to be)：
或許改到[連線容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-connect-zh)會更直覺

**Comment by VigaWei** [comment]
待 https://github.com/twcc/man-vip/milestone/4 中文 & 英文連結作業調整完成確認

**Comment by VigaWei** [comment]
[檢視運算資源概況－GPU Burn Testing](https://man.twcc.vip/docs/ccs-interactive-container/tutorials/gpu-burn-testing)

- 中文確認已連結至 [連線容器-Jupyter Notebook](https://man.twcc.vip/docs/ccs-interactive-container/user-guides/create-connect/connect-container#jupyter-notebook)

- 英文全部的連結皆待統一與中文同步，因此先略
