### ISSUE TITLE
[待調整] TWCC 會員與計畫帳務 介面和文件不一致

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#58]
- 待調整/待討論 文件連結：[管理專案成員](https://man.twcc.ai/@twsdocs/doc-mber-pjct-blng-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twsdocs%2Fguide-service-manage-project-team-zh)
- 目前狀況 (as is)：
TWS的說明文字和圖片中的「計畫」
![image](https://user-images.githubusercontent.com/67446293/181019914-8979ef17-9585-48df-8466-3b79f3b1a02c.png)
在實際操作時都是「專案」
![image](https://user-images.githubusercontent.com/67446293/179688913-a8f24f23-80c5-4584-81c6-73da5b401ab0.png)
- 理想狀況 (to be)：
更新該文件的截圖

**Comment by VigaWei** [comment]
確認已調整，謝謝!

![image](https://user-images.githubusercontent.com/46370453/188114718-53032d87-218b-4629-9703-acb2cb073f68.png)
