### ISSUE TITLE
[待調整] TWCC FAQs 連結不理想-1

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#59]
- 待調整/待討論 文件連結：[TWCC FAQs | 容器運算服務 (CCS)](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-ccs-zh#%E9%80%A3%E7%B7%9A%E7%99%BB%E5%85%A5)
- 目前狀況 (as is)：
![image](https://user-images.githubusercontent.com/67446293/181020750-a84fe3c7-523a-41ca-8151-97abb990f0e4.png)
上圖的連線容器會連結到開發型容器的服務概觀
- 理想狀況 (to be)：
或許改到[連線容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-connect-zh)更直覺

**Comment by VigaWei** [comment]
待 https://github.com/twcc/man-vip/milestone/4 中文 & 英文連結作業調整完成確認

**Comment by VigaWei** [comment]
[TWCC FAQs | 容器運算服務 (CCS)](https://man.twcc.vip/docs/faq/compute/ccs#%E9%80%A3%E7%B7%9A%E7%99%BB%E5%85%A5)

- 中文確認已連結至 [連線容器-Jupyter Notebook](https://man.twcc.vip/docs/ccs-interactive-container/user-guides/create-connect/connect-container#jupyter-notebook)

- 英文全部的連結皆待統一與中文同步，因此先略
