### ISSUE TITLE
[待調整] TWCC FAQs 連結不理想-2

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#60]
- 待調整/待討論 文件連結：[TWCC FAQs | 容器運算服務 (CCS)](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-ccs-zh#%E8%B3%87%E6%BA%90%E9%85%8D%E7%BD%AE%E8%88%87%E7%9B%A3%E6%8E%A7)
- 目前狀況 (as is)：
![image](https://user-images.githubusercontent.com/67446293/181022347-a1df9562-1c22-4810-9470-ca77cc55c247.png)
上圖的開發型容器監控頁面會連結到開發型容器的服務概觀
- 理想狀況 (to be)：
或許改成[監控容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-monitor-zh)更直覺

**Comment by VigaWei** [comment]
待 https://github.com/twcc/man-vip/milestone/4 中文 & 英文連結作業調整完成確認

**Comment by VigaWei** [comment]
[TWCC FAQs | 容器運算服務 (CCS)](https://man.twcc.vip/docs/faq/compute/ccs#%E9%80%A3%E7%B7%9A%E7%99%BB%E5%85%A5)

- 中文確認已連結至 [監控容器](https://man.twcc.vip/docs/ccs-interactive-container/user-guides/manage-monitor/monitor-container)

- 英文全部的連結皆待統一與中文同步，因此先略
