### ISSUE TITLE
[待調整] 虛擬運算服務 介面和文件不一致-1

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#61]
- 待調整/待討論 文件連結：[管理個體：停止/啟動 (與開機)/重開機/關機/刪除](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-guide-manage-instance-zh#%E5%81%9C%E6%AD%A2%E5%80%8B%E9%AB%94)
- 目前狀況 (as is)：
停止和啟動的示範截圖上沒有重開機的按鈕
![image](https://user-images.githubusercontent.com/67446293/181023356-cd4da73d-9787-42c8-93bd-72409f9ea061.png)
![image](https://user-images.githubusercontent.com/67446293/181023370-b6bbd877-ffd9-476c-9cc4-93986aa89163.png)
實際介面
![image](https://user-images.githubusercontent.com/67446293/181023408-be744a01-f101-4080-842c-bc7e8e7fe1a2.png)
- 理想狀況 (to be)：
更新文件中的截圖

**Comment by VigaWei** [comment]
確認已更新，謝謝!

![image](https://user-images.githubusercontent.com/46370453/188115012-0d53f3c9-cc84-4e92-bcbb-0f46cbfdb732.png)

![image](https://user-images.githubusercontent.com/46370453/188115047-7677aac4-10e2-4f39-9b88-305732ee1a58.png)

![image](https://user-images.githubusercontent.com/46370453/188115084-fa0cd411-6c97-4bfa-a405-e5e3101889b9.png)
