### ISSUE TITLE
[待調整] 虛擬運算服務 介面和文件不一致-2

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#62]
- 待調整/待討論 文件連結：[虛擬運算個體生命週期](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/%2F%40twccdocs%2Fconcept-vcs-lifecycle-zh)
- 目前狀況 (as is)：
停止和啟動的示範截圖上沒有重開機的按鈕
![image](https://user-images.githubusercontent.com/67446293/181024464-d17d361a-abc2-420d-a815-b0e3dbb5ef66.png)
![image](https://user-images.githubusercontent.com/67446293/181024511-4f0086bb-8f1b-4c26-bc8e-1453557406f7.png)
實際介面
![image](https://user-images.githubusercontent.com/67446293/181024398-d657b3d4-0529-4526-9df3-a4cc91ff57b9.png)
- 理想狀況 (to be)：
更新文件中的截圖

**Comment by VigaWei** [comment]
確認已更新，謝謝!

![image](https://user-images.githubusercontent.com/46370453/188115285-ce5a4995-4b3f-4b7e-8fc0-d2a499369a9b.png)

![image](https://user-images.githubusercontent.com/46370453/188115316-205033ba-7663-4a61-a9b3-1926c8f80f06.png)

![image](https://user-images.githubusercontent.com/46370453/188115344-93f446f3-3323-4747-ac9b-39203c80ae84.png)
