### ISSUE TITLE
[待調整] 開發型容器 介面和文件不一致

### ISSUE THREAD

**Issue by Oysteranpu** [twcc/man-vip#63]
- 待調整/待討論 文件連結： [開發型容器-確保計算工作持續不中斷](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fry74RpjT4%3Ftype%3Dview)

- 目前狀況 (as is)：
HackMD目前的圖如下：
![image](https://user-images.githubusercontent.com/109254397/181078003-b0b61c82-3db4-4e1c-acc7-4ce5ea5f4e5f.png)

- 理想狀況 (to be)：
實際操作左側列表與深入了解的部分稍有不同，應更新圖片
![image](https://user-images.githubusercontent.com/109254397/181077376-8b8e802c-e97e-4b14-b51e-8a3148dbfdec.png)

**Comment by VigaWei** [comment]
確認文件：https://man.twcc.vip/docs/ccs-interactive-container/tutorials/keep-processes-running-continuously

截圖已更新

- [x] zh
- [ ] en (routing 待調整，TBC)
> ![image](https://user-images.githubusercontent.com/46370453/190367957-02660c9b-f303-45f3-9fbf-72d4f5e0f0cd.png)

**Comment by VigaWei** [comment]
英文全部的連結皆待統一與中文同步，因此先略
