### ISSUE TITLE
 [中文搬家] 高速運算任務/任務型容器/release note

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#71]
### Source docs

- [高速運算任務](https://man.twcc.ai/@twccdocs/HyVzTSOpN?type=view)*1
- [任務型容器](https://man.twcc.ai/@twccdocs/HyMqnHupV?type=view)*1
- [release note (請貼英文版)](https://man.twcc.ai/@twccdocs/UserPortalHistory_EN)*1

### Target folders and files
- `docs\hpc_job`
- `docs\ccs_scheduled`
- `docs\releaseNotes`

### To-do
- refer to PPT [p.24 to p.36](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.p67)

**Comment by VigaWei** [comment]
- Michelle Est: 1hr
- Joy Est: 1hr

**Comment by Oysteranpu** [comment]
branch麻煩Viga和Mia幫我看 71-中文搬家-高速運算任務任務型容器release-note **-1**  的~
第一個Branch source點太快開到main底下QQ

**Comment by Oysteranpu** [comment]
- releaseNote裡的style有點問題，待調整

**Comment by Oysteranpu** [comment]
> * releaseNote裡的style有點問題，待調整

解決了ʕ •ᴥ•ʔ
