### ISSUE TITLE
[中文搬家] 雲端檔案服務/OneAI

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#78]
### Source docs

- [雲端檔案服務](https://man.twcc.ai/@twccdocs/doc-cfs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fcfs-overview-zh)*8
> ![](https://i.imgur.com/fPjouRe.png)
- [OneAI](https://man.twcc.ai/@twccdocs/doc-oneai-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Foneai-overview-zh)*3

> ![image](https://user-images.githubusercontent.com/46370453/181416780-0a61d347-60b6-456a-85d0-f7eb42fce783.png)

### Target folders and files
- `docs\cfs`*8
- `docs\oneai`*2
- `docs\oneai\user-guides\feature.md`*1

### To-do
- refer to PPT [p.24 to p.36](https://docs.google.com/presentation/d/1vla0LlHBrPvuCXdl09NIBvrxSPzaRRFj/edit#slide=id.p67)

**Comment by VigaWei** [comment]
Michelle Est: 1.5 hr
Joy Est: 1.5 hr

**Comment by Oysteranpu** [comment]
[熱、冷儲存區說明](https://man.twcc.ai/@twccdocs/doc-cfs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fconcept-cfs-hot-and-cold-zh)
原文件中在 資料下載區`<br>`才可取用與編輯 的部分有使用換行讓版面更好看
![image](https://user-images.githubusercontent.com/109254397/181459102-cbb67e52-f8c1-41fe-a8fe-d21f3e66d3e6.png)
但在小恐龍內換行產生問題
![image](https://user-images.githubusercontent.com/109254397/181459408-0f57af1c-031b-4216-9b53-c9301f6c5410.png)
不換行版面稍微有點不好看，目前先採用不換行
![image](https://user-images.githubusercontent.com/109254397/181458758-b3dbb566-b5bf-4558-a790-f40f5ac9c56e.png)

**Comment by VigaWei** [comment]
Hi @Oysteranpu , 使用[這個 <br/>方式](https://man.twcc.ai/fK5FdhmJTyaQ0fNGd32P3Q#2-br) 修改的話，換行會有問題嗎? 感謝!

**Comment by Oysteranpu** [comment]
> Hi @Oysteranpu , 使用[這個 `<br/>`方式](https://man.twcc.ai/fK5FdhmJTyaQ0fNGd32P3Q#2-br) 修改的話，換行會有問題嗎? 感謝!

發現我先前敘述的不太好，不算是換行發生問題，在舊文件中會在資料下載區之後換行，但新文件的表格寬度與舊的不同，所以換行會導致排版亂掉，已使用固定表格寬度的方式修正了～
