### ISSUE TITLE
[待討論] details 內的 heading

### ISSUE THREAD

**Issue by chuchun211** [twcc/man-vip#86]
⭐應非特定文件，下為狀況示意

- 待調整/待討論 文件連結：[虛擬運算服務](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-guide-connect-to-linux-from-windows-zh)
- 目前狀況 (as is)：
details 內的 heading 即便在 details 未展開時也會呈現在右側的索引
在這種情況下點擊索引並不能導至內容，顯得有些奇怪
![image](https://user-images.githubusercontent.com/67446293/181435128-8434482b-40df-4f78-914c-7e4b54c50198.png)
- 理想狀況 (to be)：
    - 將 details 的 summary 文字變為標題？（這樣右邊應該會先顯示上一級的標題）
    或
    - 移除 details 內的 heading 改為粗體（不會有索引至標題）

**Comment by VigaWei** [comment]
Thank you!

這個需要週四 meeting 討論 & 評估一下，並可能要應用到其他使用 details 的地方

就這題來看，希望是右側索引可以顯示 & 連結至 1~4 連線方式標題，details 只要展開操作的 Steps 就可以~

請先照原先的方式調整，確認修改方式後，後續的再回頭調整 🙏

**Comment by chuchun211** [comment]
討論結果⬇
<>前後空行必要

```
<details>

<summary>

## 小標題

</summary>

**Step 1. ...**
...

</details>
```

**Comment by VigaWei** [comment]
sorry，考慮方便 sync 回 HackMD，請先改為如下：

```

<details>

<summary><b>標題</b></summary>
    
<br/>

**Step 1. ...**
...

</details>

```

已加入 已加入 [搬家紀錄](https://man.twcc.ai/fK5FdhmJTyaQ0fNGd32P3Q?view#details%E7%9A%84%E6%B3%A8%E6%84%8F%E9%BB%9E-2)~
