### ISSUE TITLE
[DISCUSS] - details 變成 spoiler 樣式 & 內部列點消失-2

### ISSUE THREAD

**Issue by Oysteranpu** [twcc/man-vip#99]
## Descriptions
狀況同 [#85 ](https://github.com/twcc/man-vip/issues/85)
也是 tws-sync 新建立的 branch 發生 details 變成 spoiler的情況
(已嘗試過在第一週建立的 branch 不會發生此情況)

## 目前狀況 (as is) 
- details 變成 spoiler 樣式
![image](https://user-images.githubusercontent.com/109254397/182040820-b82e77f6-ec20-48ca-bb98-045449219926.png)

## 理想狀況 (to be)
- details 應和第一週顯示出來的樣式一樣
![image](https://user-images.githubusercontent.com/109254397/182041129-c7159c29-1505-48e8-8608-e4b739280f67.png)

## Reference:
- 待調整/待討論 文件連結：[FQA](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-product-zh)

**Comment by VigaWei** [comment]
Thank you! 

 與 #85 問題相同 & 判斷問題處理完後可以同步更新所有文件樣式

請於 85 追蹤~  先 close 🙏
